//
//  SymbolPicker.swift
//  SymbolPicker
//
//  Created by Kamil Szpak on 5/12/24.
//

import SwiftUI

public struct SymbolPicker: View {
    @Environment(\.colorScheme) var colorScheme
    @Binding public var symbolName: String
    @Binding public var colorValue: Color
    @State private var searchText = ""

    public var symbolDictionary: [String: [String]] = [
        "1_Maps":[
            "car.fill",
            "bus.fill",
            "bus.doubledecker.fill",
            "tram.fill",
            "bicycle",
            "motorcycle.fill",
            "airplane",
            "fuelpump.fill",
            "binoculars.fill",
            "mecca",
            "map.fill",
            "figure.walk",
            "location.fill",
            "mappin.and.ellipse",
            "arrow.up.and.down.and.arrow.left.and.right",
            "arrow.trianglehead.turn.up.right.diamond.fill",
            "arrow.turn.up.right",
            "figure.wave",
        ],
        "2_Devices":[
            "macpro.gen1.fill",
            "macpro.gen2.fill",
            "macpro.gen3.fill",
            "macmini.fill",
            "macstudio.fill",
            "applewatch",
            "macbook",
            "keyboard.fill",
            "printer.fill",
            "server.rack",
            "tv",
            "magsafe.batterypack.fill",
            "cable.connector",
            "applepencil.gen2",
            "magicmouse.fill",
            "computermouse.fill",
            "gamecontroller.fill",
            "headphones",
            "externaldrive.fill",
            "internaldrive.fill",
            "opticaldiscdrive.fill",
            "hearingdevice.ear.fill",
            "hifispeaker.fill",
            "tv.and.hifispeaker.fill",
            "earpods",
            "airpods",
            "airpods.gen3",
            "airpods.max",
            "airpods.pro",
            "beats.headphones",
            "beats.earphones",
            "beats.powerbeats",
            "beats.powerbeats3",
            "beats.studiobuds",
            "beats.fitpro",
            "appletv.fill",
            "homepod.fill",
            "homepod.mini.fill",
            "applewatch.radiowaves.left.and.right",
            "flipphone",
            "iphone.gen1",
            "iphone.gen3",
            "iphone.gen1.radiowaves.left.and.right",
            "iphone.gen3.radiowaves.left.and.right",
            "apps.iphone",
            "ipad.gen1",
            "ipad.gen2",
            "ipad.gen1.landscape",
            "ipad.gen2.landscape",
            "ipod",
            "scanner.fill",
            "applewatch.side.right",
            "mediastick",
            "vision.pro",
            "arcade.stick.console.fill",
        ],
        "3_Transport":[
            "car.fill",
            "airplane",
            "bus.fill",
            "bus.doubledecker.fill",
            "tram.fill",
            "tram.fill.tunnel",
            "cablecar.fill",
            "lightrail.fill",
            "ferry.fill",
            "car.ferry.fill",
            "sailboat.fill",
            "figure.walk",
            "truck.box.fill",
            "bicycle",
            "motorcycle.fill",
            "scooter",
            "wheelchair",
            "moped.fill",
            "ev.charger.fill",
        ],
        "4_Automotive":[
            "car.fill",
            "car.side.fill",
            "bolt.car.fill",
            "snowflake",
            "gauge.with.dots.needle.50percent",
            "fan.fill",
            "fuelpump.fill",
            "ev.charger.fill",
            "car.rear.fill",
            "engine.combustion.fill",
            "headlight.high.beam.fill",
            "truck.pickup.side.fill",
            "tirepressure",
            "glowplug",
            "suv.side.fill",
            "windshield.front.and.wiper",
            "oilcan.fill",
            "figure.seated.seatbelt",
            "convertible.side.fill",
            "hazardsign",
            "steeringwheel",
            "tire",
            "suspension.shock",
            "batteryblock.fill",
            "horn.fill",
        ],
        "5_Health":[
            "list.bullet.clipboard.fill",
            "heart.fill",
            "thermometer.variable",
            "microbe.fill",
            "cross.case.fill",
            "bed.double.fill",
            "lungs.fill",
            "apple.meditate",
            "pills.fill",
            "brain.fill",
            "allergens.fill",
            "medical.thermometer.fill",
            "syringe.fill",
            "stethoscope",
            "inhaler.fill",
            "facemask.fill",
            "pill.fill",
            "ivfluid.bag",
            "cross.vial.fill",
            "staroflife.fill",
            "heart.text.square.fill",
            "ivfluid.bag.fill",
            "eye.fill",
            "brain.head.profile.fill",
            "ear.fill",
            "waveform.path.ecg",
        ],
        "6_Objects & Tools":[
            "pencil",
            "eraser.fill",
            "internaldrive",
            "square.and.pencil",
            "opticaldiscdrive.fill",
            "pencil.and.scribble",
            "list.bullet.clipboard.fill",
            "chart.line.text.clipboard.fill",
            "note.text",
            "tray.full.fill",
            "highlighter",
            "pencil.and.outline",
            "internaldrive.fill",
            "lasso",
            "hat.widebrim.fill",
            "trash.fill",
            "oar.2.crossed",
            "text.document",
            "ruler.fill",
            "folder.fill",
            "paperplane.fill",
            "tray.fill",
            "tray.2.fill",
            "teddybear.fill",
            "newspaper.fill",
            "externaldrive.fill",
            "archivebox.fill",
            "document.fill",
            "link",
            "text.document.fill",
            "calendar",
            "photo.artframe",
            "book.fill",
            "crown.fill",
            "books.vertical.fill",
            "book.closed.fill",
            "text.book.closed.fill",
            "character.book.closed.fill",
            "tshirt.fill",
            "jacket.fill",
            "shoe.fill",
            "film.fill",
            "flask.fill",
            "menucard.fill",
            "magazine.fill",
            "bookmark.fill",
            "graduationcap.fill",
            "pencil.and.ruler.fill",
            "backpack.fill",
            "studentdesk",
            "paperclip",
            "lanyardcard.fill",
            "dumbbell.fill",
            "tennis.racket",
            "rosette",
            "duffle.bag.fill",
            "medal.fill",
            "fire.extinguisher.fill",
            "beach.umbrella.fill",
            "umbrella.fill",
            "megaphone.fill",
            "speaker.wave.3.fill",
            "music.microphone",
            "key.card.fill",
            "minus.plus.batteryblock.fill",
            "magnifyingglass",
            "medal.star.fill",
            "shield.fill",
            "staroflife.shield.fill",
            "flag.pattern.checkered",
            "bell.fill",
            "tag.fill",
            "bolt.shield.fill",
            "medical.thermometer.fill",
            "flashlight.on.fill",
            "camera.fill",
            "gear",
            "gearshape.2.fill",
            "frying.pan.fill",
            "scissors",
            "bag.fill",
            "cart.fill",
            "horn.fill",
            "basket.fill",
            "light.beacon.max.fill",
            "creditcard.fill",
            "wallet.pass.fill",
            "wallet.bifold.fill",
            "wand.and.sparkles",
            "faxmachine.fill",
            "puzzlepiece.fill",
            "gyroscope",
            "metronome.fill",
            "amplifier",
            "dice.fill",
            "pianokeys",
            "suitcase.rolling.fill",
            "radio.fill",
            "tuningfork",
            "printer.dotmatrix.fill",
            "paintbrush.fill",
            "paintbrush.pointed.fill",
            "poweroutlet.strip.fill",
            "level.fill",
            "wrench.adjustable.fill",
            "book.and.wrench.fill",
            "comb.fill",
            "hammer.fill",
            "screwdriver.fill",
            "fossil.shell.fill",
            "eyedropper.halffull",
            "wrench.and.screwdriver.fill",
            "hifireceiver.fill",
            "lifepreserver",
            "scroll.fill",
            "printer.fill",
            "scanner.fill",
            "handbag.fill",
            "briefcase.fill",
            "balloon.2.fill",
            "case.fill",
            "latch.2.case.fill",
            "globe.desk.fill",
            "cross.case.fill",
            "guitars.fill",
            "drone.fill",
            "helmet.fill",
            "stroller.fill",
            "movieclapper.fill",
            "suitcase.fill",
            "theatermasks.fill",
            "theatermask.and.paintbrush.fill",
            "popcorn.fill",
            "chair.fill",
            "cabinet.fill",
            "tent.fill",
            "gift.fill",
            "house.lodge.fill",
            "house.and.flag.fill",
            "signpost.left.fill",
            "signpost.right.fill",
            "signpost.right.and.left.fill",
            "building.2.fill",
            "sunglasses.fill",
            "binoculars.fill",
            "lock.fill",
            "key.fill",
            "key.2.on.ring.fill",
            "cpu.fill",
            "memorychip.fill",
            "opticaldisc.fill",
            "sensor.tag.radiowaves.forward.fill",
            "watch.analog",
            "shippingbox.fill",
            "swatchpalette.fill",
            "mug.fill",
            "wineglass.fill",
            "birthday.cake.fill",
            "scalemass.fill",
            "simcard.fill",
            "sdcard.fill",
            "waterbottle.fill",
            "cup.and.heat.waves.fill",
            "esim.fill",
            "carrot.fill",
            "battery.100percent",
        ],
        "7_Gaming":[
            "house.fill",
            "gamecontroller.fill",
            "flag.pattern.checkered",
            "flag.2.crossed.fill",
            "flag.pattern.checkered.2.crossed",
            "xmark",
            "target",
            "scope",
            "playstation.logo",
            "xbox.logo",
            "arcade.stick.console.fill",
            "formfitting.gamecontroller.fill",
        ],
        "8_Home":[
            "house.fill",
            "lightbulb.fill",
            "lamp.desk.fill",
            "sink.fill",
            "washer.fill",
            "fan.fill",
            "av.remote.fill",
            "humidifier.and.droplets.fill",
            "entry.lever.keypad.fill",
            "poweroutlet.strip.fill",
            "roller.shade.closed",
            "sensor.fill",
            "sofa.fill",
            "robotic.vacuum.fill",
            "cooktop.fill",
            "chandelier.fill",
            "video.doorbell.fill",
            "fan.floor.fill",
            "shower.fill",
            "fireplace.fill",
            "chair.lounge.fill",
            "fan.ceiling.fill",
            "lamp.ceiling.inverse",
            "homekit",
            "dishwasher.fill",
            "dryer.fill",
            "pedestrian.gate.closed",
            "shower.handheld.fill",
            "light.cylindrical.ceiling.inverse",
            "light.panel.fill",
            "blinds.vertical.open",
            "light.recessed.inverse",
            "light.recessed.3.inverse",
            "lamp.floor.fill",
            "bathtub.fill",
            "oven.fill",
            "door.garage.closed",
            "chair.fill",
            "toilet.fill",
            "microwave.fill",
            "blinds.horizontal.open",
            "lamp.table.fill",
            "fan.and.light.ceiling.fill",
            "hifireceiver.fill",
            "light.strip.2.fill",
            "stove.fill",
            "fan.desk.fill",
            "refrigerator.fill",
            "light.beacon.max.fill",
            "videoprojector.fill",
            "web.camera.fill",
            "air.purifier.fill",
            "door.left.hand.closed",
            "cabinet.fill",
            "sprinkler.and.droplets.fill",
            "spigot.fill",
        ],
        "9_Commerce":[
            "creditcard.fill",
            "cart.fill",
            "basket.fill",
            "bag.fill",
            "giftcard.fill",
            "signature",
            "eurosign",
            "centsign",
            "chineseyuanrenminbisign",
            "coloncurrencysign",
            "dongsign",
            "eurozonesign",
            "dollarsign",
            "bitcoinsign",
            "florinsign",
            "francsign",
            "indianrupeesign",
            "guaranisign",
            "danishkronesign",
            "hryvniasign",
            "kipsign",
            "larisign",
            "peruviansolessign",
            "pesetasign",
            "polishzlotysign",
            "rublesign",
            "shekelsign",
            "singaporedollarsign",
            "sterlingsign",
            "tengesign",
            "tugriksign",
            "turkishlirasign",
            "wonsign",
            "yensign",
            "nairasign",
            "norwegiankronesign",
            "malaysianringgitsign",
            "lirasign",
        ],
        "10_Weather":[
            "sun.max.fill",
            "sun.horizon.fill",
            "sun.haze.fill",
            "sun.rain.fill",
            "sun.snow.fill",
            "moon.fill",
            "moon.dust.fill",
            "cloud.heavyrain.fill",
            "moon.haze.fill",
            "sparkles",
            "moon.stars.fill",
            "cloud.fill",
            "cloud.rain.fill",
            "cloud.hail.fill",
            "cloud.snow.fill",
            "cloud.bolt.rain.fill",
            "cloud.sun.fill",
            "cloud.sun.rain.fill",
            "cloud.moon.fill",
            "smoke.fill",
            "wind",
            "snowflake",
            "tornado",
            "hurricane",
            "thermometer.variable",
            "aqi.medium",
            "rainbow",
            "cloud.rainbow.crop.fill",
        ],
        "11_Nature":[
            "carrot.fill",
            "globe.americas.fill",
            "sun.max.fill",
            "bird.fill",
            "ant.fill",
            "leaf.fill",
            "sun.dust.fill",
            "tropicalstorm",
            "lizard.fill",
            "fossil.shell.fill",
            "moonphase.waxing.crescent",
            "cloud.sleet.fill",
            "wind",
            "hurricane",
            "flame.fill",
            "water.waves",
            "ladybug.fill",
            "fish.fill",
            "drop.fill",
            "bolt.fill",
            "mountain.2.fill",
            "dog.fill",
            "atom",
            "tree.fill",
            "cat.fill",
            "apple.meditate",
        ],
        "12_Human":[
            "person.fill",
            "shareplay",
            "person.2.fill",
            "person.3.fill",
            "person.bust.fill",
            "figure.stand",
            "figure.stand.dress",
            "figure.arms.open",
            "figure",
            "figure.walk",
            "figure.fall",
            "figure.run",
            "person.wave.2.fill",
            "figure.roll",
            "figure.yoga",
            "nose.fill",
            "mustache.fill",
            "mouth.fill",
        ],
        "13_Keyboard":[
            "globe",
            "keyboard.fill",
            "command",
            "control",
            "eject.fill",
            "capslock.fill",
            "delete.left.fill",
            "power",
            "option",
            "alt",
        ],
        "14_Camera & Photos":[
            "swirl.circle.righthalf.filled",
            "circle.lefthalf.filled.righthalf.striped.horizontal",
            "circle.dotted.circle",
            "bolt.fill",
            "camera.filters",
            "livephoto",
            "camera.shutter.button.fill",
            "camera.fill",
            "camera.macro",
            "plus.viewfinder",
            "camera.viewfinder",
            "camera.aperture",
            "f.cursive",
            "photo.fill",
            
        ],
        "15_Communication":[
            "microphone.fill",
            "message.fill",
            "checkmark.message.fill",
            "bubble.fill",
            "exclamationmark.bubble.fill",
            "phone.fill",
            "phone.down.fill",
            "teletype",
            "tray.full.fill",
            "tray.2.fill",
            "video.fill",
            "deskview.fill",
            "envelope.front.fill",
            "envelope.fill",
            "envelope.open.fill",
            "waveform",
            "recordingtape",
        ],
        "16_Media":[
            "play.fill",
            "play.rectangle.fill",
            "pause.fill",
            "playpause.fill",
            "backward.fill",
            "forward.fill",
            "shuffle",
            "repeat",
            "arrow.trianglehead.clockwise",
            "infinity",
            "play.house.fill",
        ],
        "17_Connectivity":[
            "externaldrive.connected.to.line.below.fill",
            "personalhotspot",
            "network",
            "bolt.horizontal.fill",
            "icloud.fill",
            "wifi",
            "dot.radiowaves.left.and.right",
            "cellularbars",
            "bonjour",
        ],
        "18_Fitness":[
            "flame.fill",
            "dumbbell.fill",
            "sportscourt.fill",
            "surfboard.fill",
            "duffle.bag.fill",
            "soccerball",
            "baseball.fill",
            "trophy.fill",
            "medal.fill",
            "basketball.fill",
            "american.football.fill",
            "american.football.professional.fill",
            "rugbyball.fill",
            "tennis.racket",
            "hockey.puck.fill",
            "tennisball.fill",
            "volleyball.fill",
            "skateboard.fill",
            "skis.fill",
            "snowboard.fill",
            "figure.walk",
            "figure.walk.motion",
            "figure.run",
            "figure.run.treadmill",
            "figure.walk.treadmill",
            "figure.roll",
            "figure.american.football",
            "figure.archery",
            "figure.australian.football",
            "figure.badminton",
            "figure.barre",
            "figure.baseball",
            "figure.basketball",
            "figure.bowling",
            "figure.boxing",
            "figure.climbing",
            "figure.cooldown",
            "figure.core.training",
            "figure.cricket",
            "figure.skiing.crosscountry",
            "figure.cross.training",
            "figure.curling",
            "figure.dance",
            "figure.disc.sports",
            "figure.skiing.downhill",
            "figure.elliptical",
            "figure.equestrian.sports",
            "figure.fencing",
            "figure.fishing",
            "figure.flexibility",
            "figure.strengthtraining.functional",
            "figure.golf",
            "figure.gymnastics",
            "figure.hand.cycling",
            "figure.handball",
            "figure.highintensity.intervaltraining",
            "figure.hiking",
            "figure.hockey",
            "figure.field.hockey",
            "figure.ice.hockey",
            "figure.hunting",
            "figure.indoor.cycle",
            "figure.jumprope",
            "figure.kickboxing",
            "figure.lacrosse",
            "figure.martial.arts",
            "figure.mind.and.body",
            "figure.mixed.cardio",
            "figure.open.water.swim",
            "figure.outdoor.cycle",
            "oar.2.crossed",
            "figure.pickleball",
            "figure.pilates",
            "figure.play",
            "figure.pool.swim",
            "figure.racquetball",
            "figure.rolling",
            "figure.indoor.rowing",
            "figure.outdoor.rowing",
            "figure.rugby",
            "figure.sailing",
            "figure.skateboarding",
            "figure.ice.skating",
            "figure.snowboarding",
            "figure.indoor.soccer",
            "figure.outdoor.soccer",
            "figure.socialdance",
            "figure.softball",
            "figure.squash",
            "figure.stair.stepper",
            "figure.stairs",
            "figure.step.training",
            "figure.surfing",
            "figure.table.tennis",
            "figure.taichi",
            "figure.tennis",
            "figure.track.and.field",
            "figure.strengthtraining.traditional",
            "figure.volleyball",
            "figure.water.fitness",
            "figure.waterpolo",
            "figure.wrestling",
            "figure.yoga",
        ],
        "19_Accessibility":[
            "figure",
            "hand.tap.fill",
            "wheelchair",
            "apple.meditate",
            "ear.fill",
            "quote.bubble.fill",
            "plus.magnifyingglass",
            "tortoise.fill",
            "textformat.size",
            "hand.point.up.fill",
            "hearingdevice.ear.fill",
            "minus.magnifyingglass",
            "figure.stand.line.dotted.figure.stand",
            "figure.roll",
            "character.magnify",
            "hare.fill",
            "cursorarrow.motionlines",
            
        ],
        "20_Time":[
            "clock.fill",
            "deskclock.fill",
            "clock.arrow.trianglehead.2.counterclockwise.rotate.90",
            "alarm.fill",
            "alarm.waves.left.and.right.fill",
            "gauge.with.needle",
            "hourglass",
            "calendar",
            "stopwatch.fill",
            "timer",
        ],
        "21_Privacy & Security":[
            "lock.open.fill",
            "nosign",
            "lock.shield.fill",
            "exclamationmark.shield.fill",
            "touchid",
            "hand.raised.fill",
            "key.2.on.ring.fill",
            "checkmark",
            "xmark.shield.fill",
            "eye.fill",
            "eye.slash.fill",
            "lock.fill",
            "key.horizontal.fill",
            "firewall.fill",
            "checkmark.seal.fill",
            "key.fill",
            "xmark.seal.fill",
            "faceid",
        ],
        "22_Editing":[
            "pencil",
            "eraser.fill",
            "scribble.variable",
            "highlighter",
            "pencil.tip",
            "lasso",
            "beziercurve",
            "loupe",
            "inset.filled.circle.dashed",
            "scissors",
            "wand.and.rays",
            "wand.and.sparkles",
            "crop",
            "paintbrush.fill",
            "paintbrush.pointed.fill",
            "eyedropper",
            "move.3d",
            "rotate.3d.fill",
            "bandage.fill",
            "trapezoid.and.line.vertical.fill",
            "trapezoid.and.line.horizontal.fill",
            "camera.filters",
            "skew",
        ],
        "23_People":[
            "hand.thumbsup.fill",
            "hand.thumbsdown.fill",
            "person.fill",
            "person.bust.fill",
            "figure.run",
            "sunglasses.fill",
            "hand.wave.fill",
            "hand.point.left.fill",
            "hand.point.up.fill",
        ],
        "24_Symbols":[
            "square.2.layers.3d",
            "barcode",
            "qrcode",
            "inset.filled.rectangle.and.person.filled",
            "square.and.arrow.down.fill",
            "square.and.arrow.up",
            "questionmark",
            "info",
            "swift",
            "peacesign",
            "square.grid.2x2.fill",
            "ellipsis",
            "circle.dotted",
            "checklist",
            "square.grid.4x3.fill",
            "point.3.filled.connected.trianglepath.dotted",
            "rays",
            "swiftdata",
            "timelapse",
            "circle.circle",
            "airplay.audio",
            "airplay.video",
            "music.note",
            "music.note.list",
            "qrcode.viewfinder",
            "plus.square.on.square.fill",
            "waveform.path",
            "richtext.page.fill",
            "text.page.fill",
            "append.page.fill",
            "terminal.fill",
            "note.text",
            "document.fill",
            "text.document.fill",
            "dock.rectangle",
            "menubar.dock.rectangle",
            "ecg.text.page.fill",
            "questionmark.text.page.fill",
            "zipper.page",
            "person.text.rectangle.fill",
            "applescript.fill",
            "building.columns.fill",
            "sailboat.fill",
            "atom",
            "cable.connector",
            "audio.jack.stereo",
            "applepencil.adapter.usb.c.fill",
        ],
        "25_Arrows":[
            "arrowshape.left.fill",
            "arrowshape.right.fill",
            "arrowshape.left.arrowshape.right.fill",
            "arrowshape.turn.up.left.fill",
            "arrowshape.turn.up.right.fill",
            "arrow.trianglehead.counterclockwise",
            "arrow.trianglehead.2.counterclockwise.rotate.90",
            "arrow.trianglehead.topright.capsulepath.clockwise",
            "chevron.forward",
            "chevron.backward",
            "chevron.left.chevron.right",
            "arrow.down.left.arrow.up.right",
            "arrow.up.left.and.down.right.and.arrow.up.right.and.down.left",
            "arrow.up.and.down.and.arrow.left.and.right",
            "arrow.3.trianglepath",
            "arrow.2.squarepath",
            "arrow.trianglehead.branch",
        ],
        "26_Shapes":[
            "circle.fill",
            "app.fill",
            "square.fill",
            "rectangle.fill",
            "rectangle.portrait.fill",
            "capsule.fill",
            "capsule.portrait.fill",
            "oval.fill",
            "oval.portrait.fill",
            "triangle.fill",
            "triangleshape.fill",
            "rectangle.fill.on.rectangle.fill",
            "diamond.fill",
            "octagon.fill",
            "hexagon.fill",
            "pentagon.fill",
            "seal.fill",
            "rhombus.fill",
            "shield.fill",
            "xmark.triangle.circle.square.fill",
            "viewfinder",
            "button.horizontal.fill",
            "button.roundedtop.horizontal.fill",
            "button.roundedbottom.horizontal.fill",
            "button.angledtop.vertical.left.fill",
            "button.angledtop.vertical.right.fill",
            "button.angledbottom.horizontal.left.fill",
            "button.angledbottom.horizontal.right.fill",
        ],
        "27_Maths":[
            "x.squareroot",
            "angle",
            "compass.drawing",
            "sum",
            "percent",
            "function",
            "plus",
            "minus",
            "plusminus",
            "plus.forwardslash.minus",
            "multiply",
            "divide",
            "equal",
            "notequal",
            "lessthan",
            "lessthanorequalto",
            "greaterthan",
            "greaterthanorequalto",
            "number",
        ],
        "28_Indices":[
            "eurosign",
            "centsign",
            "chineseyuanrenminbisign",
            "coloncurrencysign",
            "dongsign",
            "eurozonesign",
            "dollarsign",
            "bitcoinsign",
            "florinsign",
            "francsign",
            "indianrupeesign",
            "guaranisign",
            "danishkronesign",
            "hryvniasign",
            "kipsign",
            "larisign",
            "peruviansolessign",
            "pesetasign",
            "polishzlotysign",
            "rublesign",
            "shekelsign",
            "singaporedollarsign",
            "sterlingsign",
            "tengesign",
            "tugriksign",
            "turkishlirasign",
            "wonsign",
            "yensign",
            "nairasign",
            "norwegiankronesign",
            "malaysianringgitsign",
            "lirasign",
            
        ],
        "29_Text Formatting":[
            "fleuron.fill",
            "signature",
            "list.bullet",
            "numbers",
            "textformat.size",
            "textformat",
            "textformat.superscript",
            "textformat.subscript",
            "characters.lowercase",
            "characters.uppercase",
            "bold.italic.underline",
            "paragraphsign",
            "character.magnify",
            "character.phonetic",
        ],
        
    ]

    public var body: some View {
        VStack{
            colorPicker
            searchField
            symbolsList
            Spacer()
        }
        .frame(width: 310, height: 430)
    }


    @ViewBuilder public var searchField: some View{
        List{}
            .offset(y: -10)
            .listStyle(.sidebar)
            .scrollContentBackground(.hidden)
            .searchable(text: $searchText, placement: .sidebar, prompt: "Search Symbols")
            .scrollDisabled(true)
            .frame(height: 41)
    }
    
    @ViewBuilder public var colorPicker: some View{
        LazyVGrid(columns: [GridItem(.adaptive(minimum: 21, maximum: 21))]){
            ForEach(SymbolColor.allCases){
                colorOption(for: $0)
            }
        }
        .padding(.top, 12)
        .padding(.horizontal, 7)
        
        Divider()
    }
    
    @ViewBuilder public var symbolsList: some View{
        ScrollView(.vertical){
            if searchText.isEmpty{
                let keys = symbolDictionary.keys.sorted{ Int($0.components(separatedBy: "_")[0]) ?? 0 < Int($1.components(separatedBy: "_")[0]) ?? 0}
                ForEach(keys, id: \.self){ key in
                    Section {
                        LazyVGrid(columns: [GridItem(.adaptive(minimum: 28, maximum: 28))]){
                            ForEach(symbolDictionary[key] ?? [], id: \.self){
                                symbolButton(for: $0)
                            }
                        }
                        .offset(y: -3)
                    } header: {
                        HStack{
                            Text(key.components(separatedBy: "_").last ?? "")
                                .font(.callout)
                                .fontWeight(.medium)
                                .foregroundStyle(Color.primary.opacity(0.4))
                                .padding(.horizontal, 5)
                            Spacer()
                        }
                    }
                }
                .drawingGroup()
                .padding(.horizontal, 12)
            }else{
                let items = Set(symbolDictionary.values.reduce([String]()){ $0 + $1}.filter{ $0.replacingOccurrences(of: ".", with: " ").localizedStandardContains(searchText)}).sorted()
                LazyVGrid(columns: [GridItem(.adaptive(minimum: 28, maximum: 28))]){
                    ForEach(items, id: \.self){
                        symbolButton(for: $0)
                    }
                }
                .drawingGroup()
                .offset(y: -3)
                .padding(.horizontal, 12)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .clipped()
        .offset(y: -17)
        .padding(.top, 5)
    }
    
    public func colorOption(for color: SymbolColor) -> some View{
        Button{
            colorValue = color.color
        }label:{
            Image(systemName: colorValue == color.color ? "checkmark.circle.fill" : "circle.fill")
                .resizable()
                .scaledToFit()
                .overlay(
                    Circle()
                        .stroke(.black.opacity(0.05), lineWidth: 3)
                )
                .clipShape(.circle)
                .padding(2)
        }
        .accessibilityElement()
        .accessibilityLabel(color.name)
        .accessibilityAddTraits(.isButton)
        .foregroundStyle(color.color)
        .buttonStyle(.plain)
    }
    
    
    public func symbolButton(for systemImage: String) -> some View{
        let primaryColor = colorScheme == .dark ? Color.white : Color.black
        let invertedColor = colorScheme == .dark ? Color.white : Color.black
        return Button{
            symbolName = systemImage
        }label:{
            Image(systemName: systemImage)
                .imageScale(.large)
                .frame(width: 22, height: 22)
                .fontWeight(.medium)
                .padding(.vertical, 5)
                .padding(.horizontal, 5)
                .background(primaryColor.opacity(symbolName == systemImage ? 0.25 : 0))
                .foregroundStyle(symbolName == systemImage ? invertedColor : primaryColor.opacity(0.8))
                .clipShape(RoundedRectangle(cornerRadius: 7, style: .continuous))
                .padding(.vertical, 4)
                .padding(.horizontal, 4)
                .background(.gray.opacity(0.001))
        }
        .buttonStyle(.plain)
    }
    
    public init(symbolName: Binding<String>, colorValues: Binding<[Double]>){
        self._symbolName = symbolName
        self._colorValue = Binding(get: {
            Color(red: colorValues.wrappedValue[0], green: colorValues.wrappedValue[1], blue: colorValues.wrappedValue[2])
        }, set: { newValue in
            #if canImport(UIKit)
            // Use UIColor on iOS and tvOS
            typealias NativeColor = UIColor
            #elseif canImport(AppKit)
            // Use NSColor on macOS
            typealias NativeColor = NSColor
            #endif
            
            // Variables to store the individual color components
            var r: CGFloat = 0
            var g: CGFloat = 0
            var b: CGFloat = 0
            var o: CGFloat = 1
            
            #if !os(macOS)
            // For iOS and tvOS, safely extract the color components
            guard NativeColor(newValue).getRed(&r, green: &g, blue: &b, alpha: &o) else {
                // Return default black color with full opacity if conversion fails
                colorValues = [0,0,0,1]
                return
            }
            #else
            // On macOS, convert the color to the sRGB color space and extract the RGB components; getRed(_:green:blue:alpha:) returns Void, so no guard               needed
            NativeColor(newValue).usingColorSpace(.sRGB)?.getRed(&r, green: &g, blue: &b, alpha: &o)
            #endif
            colorValues.wrappedValue = [r,g,b,o]
        })
        
    }
    
    public init(symbolName: Binding<String>, color: Binding<Color>){
        self._symbolName = symbolName
        self._colorValue = color
    }
    
    public init(symbolName: Binding<String>, symbolColor: Binding<SymbolColor>){
        self._symbolName = symbolName
        self._colorValue = .init(get: {
            symbolColor.wrappedValue.color
        }, set: { newValue in
            if let color = SymbolColor.allCases.first(where: { $0.color == newValue}){
                symbolColor.wrappedValue = color
            }
            
        })
    }
}

